[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "java -jar target/gold-api-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod"
healthcheckPath = "/api/rate/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
